server:
  port: 5000
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
        - id: LOAN-SERVICE
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/loan/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

